### ISSUE TITLE
custom implementation doesn't pass custom_initial_data_size to Init

### ISSUE THREAD

**Issue by cpetig** [cpetig/tflite_micro_compiler#17]
is it necessary to remember the size of the data and pass it to the function? I have never seen that value used.

**Comment by rafzi** [comment]
The interface requires it, so we should do it. For example I'd maybe add an assert to ensure the size in my custom op.

**Comment by cpetig** [comment]
see https://github.com/cpetig/tflite_micro_compiler/pull/21#discussion_r435247048

**Comment by cpetig** [comment]
related to #38
