### ISSUE TITLE
[FEATURE]Omit constant initializations from the table

### ISSUE THREAD

**Issue by cpetig** [cpetig/tflite_micro_compiler#37]
Don't add constant (same for all nodes/tensors) values to the info arrays but emit a statement into the for loop instead. This saves text space especially for homogenous models.

E.g.: Don't add quantization information to each tensor initialization in a non-quantized model.

**Comment by alxhoff** [comment]
I'd be happy to look into doing this one as an exercise to get more familiar with the code base

**Comment by alxhoff** [comment]
I also think that maybe we should add an option to enable the inclusion of them and extra relating helper functions. Just as I have some students that will probably make use of this tool who do not have a lot of programming experience and might benefit from additional helpers. Maybe we can add our own compiler optimization flag?

**Comment by cpetig** [comment]
Hi Alex, What is your position on the naming unification (https://github.com/cpetig/tflite_micro_compiler/issues/11), in hindsight I feel I should have used a more similar, even though less natural, making scheme for the two main functions. Best regards  Christof
