### ISSUE TITLE
[BUG] Build fails

### ISSUE THREAD

**Issue by jefffhaynes** [cpetig/tflite_micro_compiler#67]
I think I'm following the build instructions but to no avail...

`cmake.exe -DGET_TF_SRC=ON TF_TAG=v2.3.0 ..`
`make`

results in many errors, starting with:

In file included from /cygdrive/c/Users/Jeff/Source/Repos/tflite_micro_compiler/build/_deps/tf-src/tensorflow/lite/core/api/flatbuffer_conversions.h:28,
                 from /cygdrive/c/Users/Jeff/Source/Repos/tflite_micro_compiler/build/_deps/tf-src/tensorflow/lite/core/api/flatbuffer_conversions.cc:16:
/cygdrive/c/Users/Jeff/Source/Repos/tflite_micro_compiler/build/_deps/tf-src/tensorflow/lite/schema/schema_generated.h: In member function ‘bool tflite::QuantizationParameters::Verify(flatbuffers::Verifier&) const’:
/cygdrive/c/Users/Jeff/Source/Repos/tflite_micro_compiler/build/_deps/tf-src/tensorflow/lite/schema/schema_generated.h:3406:32: error: no matching function for call to ‘tflite::QuantizationParameters::VerifyField<uint8_t>(flatbuffers::Verifier&, tflite::QuantizationParameters::FlatBuffersVTableOffset) const’
 3406 |            VerifyField<uint8_t>(verifier, VT_DETAILS_TYPE) &&
      |            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~

Sorry if I'm missing something obvious.

**Comment by jefffhaynes** [comment]
Turns out the actual issue is that the README tends to omit the `-D` from arguments ;)

**Comment by rafzi** [comment]
Thank you!
