### ISSUE TITLE
Use enum for indexing g_registrations

### ISSUE THREAD

**Issue by cpetig** [cpetig/tflite_micro_compiler#7]
E.g.
g_registrations[0] = tflite::ops::micro::Register_QUANTIZE();
status = g_registrations[0]->invoke(&g_ctx, &g_nodes[0]);
becomes
g_registrations[GREG_QUANTIZE] = tflite::ops::micro::Register_QUANTIZE();
status = g_registrations[GREG_QUANTIZE]->invoke(&g_ctx, &g_nodes[0]);

especially the second change helps a lot during debugging and understanding the resulting code.

**Comment by cpetig** [comment]
I am not that happy with my choice of prefix (GREG_), though

**Comment by rafzi** [comment]
Slightly related discussion on naming:

Since all those internal definitions are in an anonymous namespace anyways: Should we drop the model naming prefix and "g_" prefix? None of the names are relevant for linking.

So for example:

``` c++
registrations[REG_QUANTIZE] = tflite::ops::micro::Register_QUANTIZE();
status = registrations[REG_QUANTIZE]->invoke(&ctx, &nodes[0]);
```

**Comment by cpetig** [comment]
> Should we drop the model naming prefix and "g_" prefix?
+1 from me
