### ISSUE TITLE
Error while generating compiler file

### ISSUE THREAD

**Issue by aryanxk02** [cpetig/tflite_micro_compiler#72]
Hi, I am trying to execute this command ```make -f tensorflow/lite/micro/tools/make/Makefile hello_world_bin``` but it throws me this error:

```
aryan@Apples-MacBook-Pro tensorflow % make -f tensorflow/lite/micro/tools/make/Makefile hello_world_bin
tensorflow/lite/micro/tools/make/Makefile:297: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/ruy'
tensorflow/lite/micro/tools/make/Makefile:297: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/ruy'
tensorflow/lite/micro/tools/make/Makefile:297: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/tools/make/Makefile:297: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
objcopy tensorflow/lite/micro/tools/make/gen/osx_x86_64/bin/hello_world tensorflow/lite/micro/tools/make/gen/osx_x86_64/bin/hello_world.bin -O binary
make: objcopy: No such file or directory
make: *** [tensorflow/lite/micro/tools/make/Makefile:351: tensorflow/lite/micro/tools/make/gen/osx_x86_64/bin/hello_world.bin] Error 127
```

I have cloned the tensorflow's repository and switched to branch `origin/r2.3` and trying to resolve the issue.

Let me know if there are any issues I have encountered while setting up.

**Comment by PhilippvK** [comment]
> `make: objcopy: No such file or directory `

the problem is that the `objcopy` executable was not found. On OSX you can probably fix it by running this command: `brew install binutils `

**Comment by aryanxk02** [comment]
> > `make: objcopy: No such file or directory `
> 
> 
> 
> the problem is that the `objcopy` executable was not found. On OSX you can probably fix it by running this command: `brew install binutils `

Hi, I did install binutils but it still throws the same error.

**Comment by aryanxk02** [comment]
Okay, I have resolved the issue.

Steps followed:

1. Get info about binutils
```
brew info binutils
```
2. Find the path displayed in the information and add it to the system.
```
export PATH=/usr/local/opt/binutils/bin:$PATH
```
